name: publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

      - run: pnpm run test
      - run: pnpm run test.e2e

      - run: yarn install --immutable
      - run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: yarn vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: yarn vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
