name: publish
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.x
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --no-optional

      - name: lint
        run: pnpm run lint

      - name: format
        run: pnpm run fmt.check

      - name: build
        run: pnpm run build

      - name: Run unit test
        run: pnpm run test

      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30

      # - name: Build App
      #   run: pnpm run build
      # - run: pnpm install --immutable
      # - run: pnpm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      # - run: pnpm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      # - run: pnpm vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
