name: publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          version: 18.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.x
          run_install: false

      - name: Install dependencies
        run: pnpm install

      # - name: Build App
      #   run: pnpm run build

      # - name: Run unit test
      #   run: pnpm run test

      # - name: Run e2e test
      #   run: pnpm run test.e2e

      # - run: pnpm install --immutable
      # - run: pnpm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      # - run: pnpm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      # - run: pnpm vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
